name: satellite
channels:
  - conda-forge
dependencies:
  - python>=3.7,<3.10
  - ca-certificates
  - toml
  - openssl
  - pandas
  - html5lib 
  - lxml
  - beautifulsoup4
  - pillow
  - tqdm
  - pyproj
  - owslib
  - ipykernel
  - certifi
  - ipywidgets
  - black
  - starlite
  - uvicorn
  - picologging
  - pytest
  - pip
  - pip:
      - --extra-index-url https://google-coral.github.io/py-repo/
      - pycoral~=2.0
      - tflite-runtime
