name: Python package

on: [push]

defaults:
  run:
    shell: bash -l {0}
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-env: true
          extra-specs: |
            black
            pytest

      - name: Lint with black
        uses: psf/black@stable
        with:
          jupyter: true

      - name: Test with pytest
        run: |
          pytest tests/